# Nixpacks configuration for Railway deployment with OpenCV support
providers = ["python"]

[phases.setup]
# Use apt packages for OpenCV dependencies (more reliable than Nix packages)
aptPkgs = [
  "libgl1-mesa-glx",
  "libglib2.0-0"
]

[start]
cmd = "python release.py && gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120 --log-level info --access-logfile - --error-logfile -"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
